# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data do saldo inicial'),
        ),
    ]
